### ISSUE TITLE
Canvas mode not working

### ISSUE THREAD

**Issue by petersonross89** [FlightOne/FalcoX-Issue-Tracker#284] opened 2021-11-18 02:12 UTC
**Version**
10.1.1.5792

**Target**
Revolt osd

**Describe the bug**
When updating to latest hdzero firmware(28102021) on sharkbyte rx and tx canvas mode no longer works on falco x .i tested to confirm it was falco x by flashing betaflight and then canvas mode works again or also downgrading hdzero firmware (23072021)canvas mode works again on falco x.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by PGIII** [comment] 2021-11-18 15:03
Closing due to being duplicate of #279

**Closed by PGIII** 2021-11-18 15:03 UTC
Labels: bug, firmware
