### ISSUE TITLE
Iflight F722 not working

### ISSUE THREAD

**Issue by crashingdrones** [FlightOne/FalcoX-Issue-Tracker#234] opened 2021-06-07 20:12 UTC
**Version**
FLX_IFLIGHTF722_TWING_10.1.0.5490

**Target**
Iflight twingF722

**Describe the bug**
Iflight F7 doesn't detect anything when you plug it in with DJI remote etc.

**To Reproduce**
try to configure iflight f722 with dji remote and goggles..... won't even connect...

**Comment by flymott** [comment] 2021-06-09 01:12
Yea i m having the same issue too :((

**Comment by PGIII** [comment] 2021-06-09 14:35
Do you have a link to what board you using and how do you have the receiver connected

**Comment by PGIII** [comment] 2021-06-09 14:40
This is also a duplicate of #179 so please respond on there with what Board you're using and how the Receiver is connected

**Closed by PGIII** 2021-06-09 14:40 UTC
Labels: bug, firmware
