### ISSUE TITLE
OSD CrossHair not aligned on Center DJI Goggles Tmotor F7 FC

### ISSUE THREAD

**Issue by Jurisjury** [FlightOne/FalcoX-Issue-Tracker#235] opened 2021-06-18 15:04 UTC
**Describe the bug**
OSD Crosshair not aligned on center in DJI goggles 

**Expected behavior**
When using the Crosshair it should be at the center of the Screen Display

**Desktop (please complete the following information):**
Falco flashed on Tmotor F7 HD Flight Controller
Version 10.1.0.5503

**Additional context**

**Comment by PGIII** [comment] 2021-06-25 20:39
This is a duplicate of #198

**Closed by PGIII** 2021-06-25 20:39 UTC
Labels: bug, configurator
