### ISSUE TITLE
[FEATURE] Able to turn on/off start up beeps

### ISSUE THREAD

**Issue by felipeng** [FlightOne/FalcoX-Issue-Tracker#228] opened 2021-05-20 18:06 UTC
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
Option on the OSD to enable/disable the beeps on start up

**Describe alternatives you've considered**
N/A

**Additional context**
On stable firmware the beeper was silence during start up, however on alpha every time I plug the battery the beeper does like 10 beeps starting very loud and decreasing.
It's very annoying, when I am doing some maintenance during nights and don't want to wake up my whole family.

**Comment by PGIII** [comment] 2021-05-20 18:45
This is a duplicate of #172 , feature is planned for a future Alpha release

**Closed by PGIII** 2021-05-20 18:45 UTC
Labels: enhancement, firmware
