### ISSUE TITLE
REVOLT OSD - Crossfire 50hz failsafe 

### ISSUE THREAD

**Issue by loutwice** [FlightOne/FalcoX-Issue-Tracker#91] opened 2021-01-10 04:08 UTC
**Version**
FLX_REVOLT_10.0.18.4939 

**Target**
RevoltOSD
tango 2 pcb v1 

**Describe the bug**
when crossfire is set at 50hz - it failsafe 

**To Reproduce**
set crossfire to 50 hz - 
arm the kwad play with the throttle you will already feel a delay 
and it failsafe

**Expected behavior**
not failsafe 

**Additional context**
Beta firmware FLX_REVOLT_10.0.6.3923 works really well no problem at all

**Comment by PGIII** [comment] 2021-01-11 18:25
Do you still have this issue on the latest alpha version ?

**Comment by loutwice** [comment] 2021-01-11 22:57
> Do you still have this issue on the latest alpha version ?

yes and it comes even faster than before

**Comment by loutwice** [comment] 2021-01-13 23:43
let me know if you want special test or anything else

**Comment by PGIII** [comment] 2021-01-17 23:39
[FLX_REVOLT_10.1.0.5160_SERIAL_DEBUG_INFO.zip](https://github.com/FlightOne/FalcoX-Issue-Tracker/files/5827025/FLX_REVOLT_10.1.0.5160_SERIAL_DEBUG_INFO.zip)
Can you get a DVR with this

**Comment by loutwice** [comment] 2021-01-21 11:05
> [FLX_REVOLT_10.1.0.5160_SERIAL_DEBUG_INFO.zip](https://github.com/FlightOne/FalcoX-Issue-Tracker/files/5827025/FLX_REVOLT_10.1.0.5160_SERIAL_DEBUG_INFO.zip)
> Can you get a DVR with this

back from holydays ! sorry for the delay ! here is the video let me know if you need more 

https://user-images.githubusercontent.com/7931460/105342678-c1897d00-5c34-11eb-8e08-7c98ec6893fb.mp4

**Comment by PGIII** [comment] 2021-01-23 17:18
Hmm thats pretty Strange, doesnt look like a Serial Port issue, ill have to give you another Test bin, do you have the VTX attached to the Receiver or anything like that ? and how come you use 50hz do the faster speeds not have an issue ?

**Comment by loutwice** [comment] 2021-01-23 20:56
> Hmm thats pretty Strange, doesnt look like a Serial Port issue, ill have to give you another Test bin, do you have the VTX attached to the Receiver or anything like that ? and how come you use 50hz do the faster speeds not have an issue ?

Yes I use tbs vtx linked to the tbs nano so I can change power and channel directly in the crossfire menu from the remote - I will have to retry with 150 hz to confirm you if it works - 

Yesterday for a work I flew 10.0.6.2823 - no problem with that old one. If you want I can try all firmware that went out from this one so we can find from when it is happening - just throw me the firmwares you want me to test -

**Comment by loutwice** [comment] 2021-01-29 02:50
forget to mention it happens also with without vtx on nano rx ( got an hd kwad behave the same ) i will try it soon on H7 see if it happens

**Comment by PGIII** [comment] 2021-03-16 21:11
Closing since this seems to be caused by the same problem as #144

**Closed by PGIII** 2021-03-16 21:11 UTC
Labels: bug, firmware
