### ISSUE TITLE
3 profiles tune not well restored

### ISSUE THREAD

**Issue by ElMute** [FlightOne/FalcoX-Issue-Tracker#26] opened 2020-04-06 23:12 UTC
the 3 profile set up are not well saved and restored with configurator 2,02 and alpha 3065

edit the 3 setup, backup it, and try to restore it, only one of the 3 setup is well restored

**Comment by PGIII** [comment] 2020-04-07 17:00
The configurator doesnt support the multiple updates yet that will come in its next update

**Comment by PGIII** [comment] 2020-05-18 23:56
Closing since this is a duplicate of #43

**Closed by PGIII** 2020-05-18 23:56 UTC
Labels: configurator, duplicate, enhancement
