### ISSUE TITLE
[NEW TARGET] KAKUTEF7 30X30 FLIGHTCONTROLLER

### ISSUE THREAD

**Issue by OTTOCROMAFPV** [FlightOne/FalcoX-Issue-Tracker#151] opened 2021-02-13 07:59 UTC
---
name: KAKUTEF7 
title: "[NEW TARGET] New Target For Firmware"
labels: KAKUTEF7, FALCOX
assignees: ''

**Comment by OTTOCROMAFPV** [comment] 2021-02-13 08:04
Holybro Kakute F7 V1.5 STM32F745


[https://www.google.com/search?q=KAKUTE+F7&rlz=1C5CHFA_enIT877IT877&sxsrf=ALeKk01MayOnObRo4QZ8VAD9e34XC-SLZg:1613203386224&source=lnms&tbm=isch&sa=X&ved=2ahUKEwiv4KT2subuAhW8DWMBHT39Bp0Q_AUoAXoECAYQAw&biw=1425&bih=724]

**Comment by PGIII** [comment] 2021-02-13 16:36
Duplicate of #139

**Closed by PGIII** 2021-02-13 16:36 UTC
Labels: firmware, new target
