### ISSUE TITLE
Mac and 4657 Does not work most of the time

### ISSUE THREAD

**Issue by 2dogrc** [FlightOne/FalcoX-Issue-Tracker#68] opened 2020-11-19 16:11 UTC
10.0.11 Config and 4657
If FC is plugged in first, Config won't connect, show connect to Revolt Version 0.0.0.0 in the upper left corner
If FC is plugged and then unplugged/ejected from file manager and plugged back in again will not show up.
If FC is plugged in, then drive ejected, then open the config works much faster.
   However if then the FC is disconnected and then plugged back in, the config does not work again.

**Comment by PGIII** [comment] 2020-12-01 22:00
closing since duplicate of #77

**Closed by PGIII** 2020-12-01 22:00 UTC
Labels: bug, configurator
